---
title: "Scott Farm Data"
author: "Simon Woodward"
date: "November 2, 2017"
output: word_document
---

```{r setup, include=FALSE}
# echo=FALSE (hide R code)
# results=markup, results=asis, results=hide
# warning=FALSE, message=FALSE, error=TRUE
# fig.keep=none, fig.keep=all, fig.keep=high  
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, tidy=FALSE, results='hide', fig.keep='all', fig.width=9)
remove(list=ls())

# load libraries
# "lubridate" %in% (.packages()) # how to check if package loaded
library(tidyverse)
library(readxl)
library(stringr)
library(scales)
library(lubridate)
library(RColorBrewer)

# automatically convert text to something easy to work with
ensnakeify <- function(x) {
  x %>%
    iconv(to="ASCII//TRANSLIT") %>% # remove accents
    str_replace_na() %>% # convert NA to string
    str_to_lower() %>% # convert to lower case
    str_replace_all(pattern="[^[:alnum:]]", replacement=" ") %>% # convert non-alphanumeric to space
    str_trim() %>% # trim leading and trailing spaces
    str_replace_all(pattern="\\s+", replacement="_") # convert remaining spaces to underscore
}

round_any = function(x, accuracy, f=round){
  if (is.Date(x)){
    switch(f,
           round=round_date(x, accuracy),
           ceiling=ceiling_date(x, accuracy),
           floor=floor_date(x, accuracy)
    )
  } else {
    f( x / accuracy) * accuracy
  }
}

# my_trans <- function(x){trans_new('my', 
#             transform = function(y){0.01*y},
#             inverse   = function(y){100*y}
#             )}

```

## Scott Farm Data

```{r}
# file name
file_name <- 'FD1004 Data For Modelling.xlsx'

# seed rates in order
seed_rate_levels <- c('6kg', '12kg', '18kg', '24kg', '30kg')
```

## Rising Plate Meter

```{r }
# read rpm data. Some extra stuff in this sheet!
data_rpm <- read_xlsx(file_name, sheet='Waikato RPM Height data')
names(data_rpm) <- ensnakeify(names(data_rpm))

# rename useful variables
data_rpm <- data_rpm %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
       date_pre = date_pre_rpm_d,
       mass_pre = pregrazing_mass_kg_dm_ha,
       date_post = date_post_rpm_d,
       mass_post = postgrazing_mass_kg_dm_ha,
       date_grazed = date_grazed_d
       ) %>%
  select(date_grazed, block, cultivar, seed_rate, date_pre, mass_pre, date_post, mass_post)

# plot pre and post mass by cultivar, seed_rate and block
ybreaks <- seq(0, round_any(max(data_rpm$mass_pre, na.rm=TRUE), 2000, ceiling), 2000)
xbreaks <- seq(floor_date(min(data_rpm$date_pre), "years"), 
               ceiling_date(max(data_rpm$date_post), "years"), by="1 year")
data_rpm %>%
  split(.$block) %>%
  map(~ggplot(.) +
        labs(x='Date', y='Plate mass (kgDM/ha)', 
          title=paste('Pre and post plate mass (to ground level), Block', unique(.$block))) +
        theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
        geom_vline(mapping=aes(xintercept=date_grazed), colour='grey') +
        geom_point(mapping=aes(x=date_pre, y=mass_pre), colour='red') +
        geom_point(mapping=aes(x=date_post, y=mass_post), colour='blue') +
        facet_grid(cultivar ~ seed_rate) +
        scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
        scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
      )

```

## Rising Plate Meter Harvest %

```{r}
# plot harvest % by cultivar, seed_rate and block
data_rpm <- data_rpm %>%
  mutate(harv = (1 - mass_post / mass_pre) * 100)

ybreaks <- seq(0, round_any(max(data_rpm$harv, na.rm=TRUE), 20, ceiling), 20)
xbreaks <- seq(floor_date(min(data_rpm$date_pre), "years"), 
               ceiling_date(max(data_rpm$date_post), "years"), by="1 year")
data_rpm %>%
  split(.$block) %>%
  map(~ggplot(.) +
        labs(x='Date', y='Harvest %', 
             title=paste('Harvest %, Block', unique(.$block))) +
        theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
        geom_vline(mapping=aes(xintercept=date_grazed), colour='grey') +
        geom_point(mapping=aes(x=date_grazed, y=harv), colour='purple') +
        facet_grid(cultivar ~ seed_rate) +
        scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
        scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
      )

```

## Pasture Cuts Mass

```{r }
# read cut data
data_cut1 <- read_xlsx(file_name, sheet='Cut Yield Data Year1 2011to12')
data_cut2 <- read_xlsx(file_name, sheet='Cut Yield Data Year2 onwards')
names(data_cut1) <- ensnakeify(names(data_cut1))
names(data_cut2) <- ensnakeify(names(data_cut2))

# rename useful variables
data_cut1 <- data_cut1 %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
    date = date_d,
    yield = yield_kg_dm_ha
  ) %>%
  mutate(
    month = month(month)
  ) %>%
  group_by(date, block, seed_rate, cultivar) %>%
  summarise(yield = mean(yield))

# rename useful variables
data_cut2 <- data_cut2 %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
    date = date_d,
    yield = yield_kg_dm_ha,
    dm_pc = mean_dm
  ) %>%
  mutate(
    month = month(month)
  ) %>%
  select(date, block, seed_rate, cultivar, yield, dm_pc)

# combine tables by row keeping common variables
data_cut <- full_join(data_cut1, data_cut2)

# cutting dates for matching with other data sets
date_cut <- unique(data_cut$date)
closest_date_cut <- function(date){ # return index of closest date_cut
  i <- which(abs(date-date_cut)==min(abs(date-date_cut)))[[1]]
}

# plot yield data
ybreaks <- seq(0, round_any(max(data_cut$yield, na.rm=TRUE), 1000, ceiling), 1000)
xbreaks <- seq(floor_date(min(data_cut$date), "years"), 
               ceiling_date(max(data_cut$date), "years"), by="1 year")
data_cut %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Cut mass (kgDM/ha)', 
         title=paste('Pasture Cut mass (pregrazing, cut to 4cm), Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_vline(data=data_rpm, mapping=aes(xintercept=date_grazed), colour='grey') +
    geom_point(mapping=aes(x=date, y=yield), colour='red') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
  )

```

## Mass Below Cutting Height

```{r}
# find cut matching rpm data
data_rpm$date_cut_i <- lapply(data_rpm$date_pre, closest_date_cut)
data_rpm$date_cut <- date_cut[unlist(data_rpm$date_cut_i)]

# join cut and rpm data by date_cut
data_cut$date_cut <- data_cut$date
data_bc <- data_rpm %>%
  left_join(data_cut, by=c('date_cut', 'block', 'seed_rate', 'cultivar')) %>%
  select(date_pre, date_cut, block, seed_rate, cultivar, mass_pre, yield) %>%
  mutate(delay = as.integer(as.Date(date_cut) - as.Date(date_pre))) %>% 
  filter(abs(delay)<4) %>%
  drop_na() %>%
  mutate(below = mass_pre - yield)
         
# copy below back into data_cut
data_cut <- data_cut %>%
  left_join(data_bc, by=c('date_cut', 'block', 'seed_rate', 'cultivar')) %>%
  select(date, block, seed_rate, cultivar, yield.x, dm_pc, date_cut, date_pre, mass_pre, delay, below) %>%
  rename(yield=yield.x)
  
# plot below cutting mass
ybreaks <- seq(0, round_any(max(data_bc$below, na.rm=TRUE), 1000, ceiling), 1000)
xbreaks <- seq(floor_date(min(data_bc$date_pre), "years"), 
               ceiling_date(max(data_bc$date_pre), "years"), by="1 year")
data_bc %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Dry weight (kgDM/ha)', fill='Species',
         title=paste('Mass Below Cut (below 4cm), Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_point(mapping=aes(x=date_pre, y=below), colour='brown') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
  )

```

## Pasture Cuts DM%

```{r }
# plot DM% data
ybreaks <- seq(0, round_any(max(data_cut$dm_pc, na.rm=TRUE), 10, ceiling), 10)
xbreaks <- seq(floor_date(min(data_cut$date), "years"), 
               ceiling_date(max(data_cut$date), "years"), by="1 year")
data_cut %>%
  split(.$block) %>%
  map(~ggplot(.) +
  labs(x='Date', y='Dry matter %', 
       title=paste('Pregazing Dry Matter % (cut to 4cm), Block', unique(.$block))) +
  theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
  geom_vline(data=data_rpm, mapping=aes(xintercept=date_grazed), colour='grey') +
  geom_point(mapping=aes(x=date, y=dm_pc), colour='purple') +
  facet_grid(cultivar ~ seed_rate ) +
  scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
  scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
  )

```

## Tiller Density

```{r }
# read tiller data
data_till <- read_xlsx(file_name, sheet='Tiller density data Waikato')
names(data_till) <- ensnakeify(names(data_till))

# rename useful variables
data_till <- data_till %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
    date = date_d,
    tillers = ryegrass_tiller_density_tillers_m2
  ) %>%
  group_by(block, cultivar, seed_rate, date) %>%
  summarise(mean_tillers = mean(tillers))

# plot tiller data ~(mg~L^{-1})
ybreaks <- seq(0, round_any(max(data_till$mean_tillers, na.rm=TRUE), 2500, ceiling), 2500)
xbreaks <- seq(floor_date(min(data_till$date), "years"), 
               ceiling_date(max(data_till$date), "years"), by="1 year")
data_till %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Tiller density'~(tillers~m^{2}), 
         title=paste('Tiller Density, Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_vline(data=data_rpm, mapping=aes(xintercept=date_grazed), colour='grey') +
    geom_point(mapping=aes(x=date, y=mean_tillers), colour='darkgreen') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, 
                       limits=c(ybreaks[1], round_any(max(data_till$mean_tillers, na.rm=TRUE), 1000, ceiling)))
  )

```

## Botanical Composition

```{r }
# read botanical data. skip blank line at top
data_bot <- read_xlsx(file_name, sheet='Botanical Composition data ', skip=1)
names(data_bot) <- ensnakeify(names(data_bot))

# rename useful variables
data_bot <- data_bot %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
    date = date_d,
    leaf = perennial_ryegrass_leaf,
    stem = perennial_ryegrass_reproductive_stem,
    ann = annual_ryegrass,
    wc = white_clover,
    poa = poa_sp,
    ogx = other_grasses_excluding_poa,
    og = other_grasses_including_poa,
    weed = weeds,
    dead = dead
    ) %>%
  mutate(
    total = leaf + stem + ann + wc + og + weed + dead, # should always be 100
    month = month(dmy(paste('01', month, '2011')))
  ) %>%
  select(leaf, stem, ann, wc, og, weed, dead, date, total, block, seed_rate, cultivar) 
  
# gather
data_bot2 <- data_bot %>%
  gather(leaf, stem, ann, wc, og, weed, dead, key='species', value='fraction') %>%
  mutate(species = factor(species, 
                          levels=c('leaf', 'stem', 'ann', 'og', 'wc', 'weed', 'dead')))

# plot botanical data
ybreaks <- seq(0, 100, 20)
xbreaks <- seq(floor_date(min(data_bot2$date), "years"), 
               ceiling_date(max(data_bot2$date), "years"), by="1 year")
data_bot2 %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Dry weight %', fill='Species',
         title=paste('Botanical composition (cut to 4cm), Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_bar(mapping=aes(x=date, y=fraction, fill=species), stat='identity') +
    scale_fill_brewer(palette='Paired') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))
  )

```

## Botancial Mass

```{r}
# find cut matching botanical data
data_bot$date_cut_i <- lapply(data_bot$date, closest_date_cut)
data_bot$date_cut <- date_cut[unlist(data_bot$date_cut_i)]

# join cut and botanical data by date_cut
data_cut$date_cut <- data_cut$date
data_bm <- data_bot %>%
  rename(date_bot = date) %>%
  left_join(data_cut, by=c('date_cut', 'block', 'seed_rate', 'cultivar')) %>%
  select(date_bot, date_cut, block, seed_rate, cultivar, leaf, stem, ann, wc, og, weed, dead, yield, below) %>%
  mutate(
    delay = as.integer(as.Date(date_cut) - as.Date(date_bot)),
    yield2 = yield + below
    )
         
# gather
data_bm2 <- data_bm %>%
  gather(leaf, stem, ann, wc, og, weed, dead, key='species', value='fraction') %>%
  mutate(
    species = factor(species, levels=c('leaf', 'stem', 'ann', 'og', 'wc', 'weed', 'dead')),
    species_mass = fraction / 100 * yield # include mass below cutting?
    ) 

# plot botanical data
ybreaks <- seq(0, round_any(max(data_bm2$yield, na.rm=TRUE), 1000, ceiling), 1000)
xbreaks <- seq(floor_date(min(data_bm2$date_cut), "years"), 
               ceiling_date(max(data_bm2$date_cut), "years"), by="1 year")
data_bm2 %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Dry weight (kgDM/ha)', fill='Species',
         title=paste('Herbage Mass Fractions (above 4cm), Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_point(mapping=aes(x=date_cut, y=yield), colour='grey', size=2, shape=1) +
    geom_bar(mapping=aes(x=date_cut, y=species_mass, fill=species), stat='identity') +
    scale_fill_brewer(palette='Paired') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=year(xbreaks), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], 
                                                round_any(max(data_bm2$yield, na.rm=TRUE), 100, ceiling)))
  )

```

## Light Interception

```{r }
# read li data
data_li <- read_xlsx(file_name, sheet='Waikato LightInterception')
names(data_li) <- ensnakeify(names(data_li))

# rename useful variables
data_li <- data_li %>%
  mutate(
    block = floor((plot-1)/20)+1, # this needs to be checked 
    seed_rate = factor(seed_rate, levels=seed_rate_levels)
    ) %>%
  rename(
    date = date,
    date_grazed = date_last_grazed,
    li = light_interception
  ) %>%
  select(date, block, seed_rate, cultivar, li, date_grazed)

# plot light interception data
ybreaks <- seq(0, round_any(max(data_li$li, na.rm=TRUE), 25, ceiling), 25)
xbreaks <- seq(floor_date(min(data_li$date), "months"), 
               ceiling_date(max(data_li$date), "months"), by="1 month")
data_li %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Light interception %', 
         title=paste('Light Interception 2011, Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_vline(data=data_rpm, mapping=aes(xintercept=date_grazed), colour='grey') +
    geom_point(mapping=aes(x=date, y=li), colour='magenta') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=format(xbreaks, "%b-%Y"), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))

  )

```

## Soil Moisture

```{r}
# read soil moisture data
data_sm <- read_xlsx(file_name, sheet='Soil moisture data')
names(data_sm) <- ensnakeify(names(data_sm))

# rename useful variables
data_sm <- data_sm %>%
  mutate(seed_rate = factor(seed_rate, levels=seed_rate_levels)) %>%
  rename(
    date = date_measured_d,
    sm = soil_moisture
  ) %>%
  group_by(block, cultivar, seed_rate, date) %>%
  summarise(mean_sm = mean(sm))

# plot sol moisture data
ybreaks <- seq(0, round_any(max(data_sm$mean_sm, na.rm=TRUE), 20, ceiling), 20)
xbreaks <- seq(floor_date(min(data_sm$date), "months"), 
               ceiling_date(max(data_sm$date), "months"), by="1 month")
data_sm %>%
  split(.$block) %>%
  map(~ggplot(.) +
    labs(x='Date', y='Soil Moisture %', 
         title=paste('Soil Moisture 2017, Block', unique(.$block))) +
    theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1)) +
    geom_vline(data=data_rpm, mapping=aes(xintercept=date_grazed), colour='grey') +
    geom_point(mapping=aes(x=date, y=mean_sm), colour='blue') +
    facet_grid(cultivar ~ seed_rate ) +
    scale_x_datetime(breaks=xbreaks, labels=format(xbreaks, "%b-%Y"), limits=c(xbreaks[1], tail(xbreaks, 1))) +
    scale_y_continuous(breaks=ybreaks, limits=c(ybreaks[1], tail(ybreaks, 1)))

  )
```

## Calculations

```{r}
# move post harvest measurements
data_rpm$date_post2 <- as.Date(with(data_rpm,
                            ifelse(date_post > date_grazed, 
                                   as.Date(date_post), 
                                   as.Date(date_post) + 1)
                            ), origin="1970-01-01")

# some calculations
data_rpm <- data_rpm %>%
  mutate(
    year_pre = year(date_pre),
    doy_pre = yday(date_pre),
    year_post = year(date_post2),
    doy_post = yday(date_post2),
    year_grazed = year(date_grazed),
    doy_grazed = yday(date_grazed), 
    days_pre = difftime(date_grazed, date_pre, units="days"),
    days_post = difftime(date_post2, date_grazed, units="days")
    )

# choose data
acultivar <- 'Alto' # only Alto and Halo have light interception data
aseed_rate <- '18kg'
ablock <- 3

```

## Write Harvest Dates

```{r}
# write harvest dates for selected series
data_h <- data_rpm %>%
  select(block, seed_rate, cultivar, year_grazed, doy_grazed, harv) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) %>%
  drop_na()
days_harvest <- matrix(as.integer(-1), nrow=100, ncol=3) # up to 100 harvests
days_harvest[1:nrow(data_h),] <- c(data_h$year_grazed, data_h$doy_grazed, data_h$harv)
write.table(days_harvest, file="harvest_Scott.txt", 
            row.names=FALSE, col.names=FALSE, sep='\t')

```

## Write Calibration Data

```{r}
# collect the data in this list
data_c <- vector("list", 6) 

# pre and post mass (this includes other species!)
temp <- data_rpm %>%
  select(block, seed_rate, cultivar, mass_pre, year_pre, doy_pre, 
         mass_post, year_post, doy_post) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) 
data_c[[1]] <- with(temp, tibble(var='DM', year=year_pre, 
                                 doy=doy_pre, data=mass_pre/10) %>% drop_na())
data_c[[2]] <- with(temp, tibble(var='DM', year=year_post, 
                                 doy=doy_post, data=mass_post/10) %>% drop_na())

# ryegrass tillers
temp <- data_till %>%
  select(block, seed_rate, cultivar, mean_tillers, date) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) 
data_c[[3]] <- with(temp, tibble(var='TILTOT', year=year(date), 
                                 doy=yday(date), data=mean_tillers) %>% drop_na())

# ryegrass fraction
temp <- data_bot %>%
  select(block, seed_rate, cultivar, leaf, stem, date) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) 
data_c[[4]] <- with(temp, tibble(var='CSTP', year=year(date), 
                                 doy=yday(date), data=stem/(leaf+stem)*100) %>% drop_na())

# light interception
temp <- data_li %>%
  select(block, seed_rate, cultivar, li, date) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) 
data_c[[5]] <- with(temp, tibble(var='LINT', year=year(date), 
                                 doy=yday(date), data=li) %>% drop_na())

# soil moisture
temp <- data_sm %>%
  select(block, seed_rate, cultivar, mean_sm, date) %>%
  filter(block==ablock & seed_rate==aseed_rate & cultivar==acultivar) 
data_c[[6]] <- with(temp, tibble(var='WCL', year=year(date), 
                                 doy=yday(date), data=mean_sm) %>% drop_na())

# bind list and write file
data_calib <- bind_rows(data_c)
data_calib <- arrange(data_calib, var, year, doy)
write.table(data_calib, file="data_calibration_Scott.txt", 
            row.names=FALSE, col.names=FALSE, sep='\t', quote=FALSE)

```

